#!/bin/bash

if [ $# -lt 2 ]; then
	echo "Error: gimme requires 2 arguments."
	exit 1
fi

script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

case "$1" in
    "c")
        mkdir $2
        cd $2
        cp -r "$script_directory/templates/c_template/"* .
	;;
    "glfw")
        mkdir $2
	cd $2
	cp -r ./templates/glfw_2d_template/* .
	;;
    *)
        echo "Error: template named \"$1\" not found."
	exit 1
	;;
esac


